<?php

/**
 * Do not edit this file. Edit the config files found in the config/ directory instead.
 *
 * This file is required in the web root so WordPress can find it.
 * WordPress is hard-coded to look in its own directory (web/wp) or one directory
 * up (web/) for wp-config.php.
 *
 * Tracked Bedrock entrypoint. Loads the Composer autoloader and the shared
 * application configuration from config/application.php, then bootstraps
 * WordPress core (wp-settings.php).
 */

require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';